### ISSUE TITLE
コードの最適化

### ISSUE THREAD

**Issue by ryusuke920** [m-atarashi/word_cloud#1]
https://github.com/m-atarashi/word_cloud/blob/874d121afb4b43baa1b3c8c8c5fa5a970c9413b3/sample_ja.py#L23

```python
    one_char_filter = set(f.read().split('\n'))
```
の方がオーダー的には早いです.

(空白は半角 4 つ です)

**Comment by m-atarashi** [comment]
`in list` は O(n) で `in set` は定数オーダーなんですね．ありがとうございます．
